// User (Login, Register, Edit)
export const LOGIN_USER = "LOGIN_USER";
export const INVALID_USER = "INVALID_USER";
export const REGISTER_USER = "REGISTER_USER";
export const EDIT_USER = "EDIT_USER";

// Products
export const FETCH_COLLECTION = "FETCH_COLLECTION";
export const FETCH_COLLECTION_BY_CATEGORY = "FETCH_COLLECTION_BY_CATEGORY";
export const FETCH_COLLECTION_BY_PRICE = "FETCH_COLLECTION_BY_PRICE";
export const FETCH_COLLECTION_BY_RATING = "FETCH_COLLECTION_BY_RATING";
export const FETCH_PRODUCT = "FETCH_PRODUCT";

// Cart
export const FETCH_CART = "FETCH_CART";
export const ADD_TO_CART = "ADD_TO_CART";